### ISSUE TITLE
More detailed README

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/policybrain-builder#3]
E.g. which env vars do I use, do I have to update B-Tax and OG-USA every time Tax-Calc is released (yes)?

**Comment by martinholmer** [comment]
Pull request #52 by @jbcrail made issue #3 obsolete. Thanks, @jbcrail.
But maybe the contents of the `README-cli.md` should be moved to the `README.md` file.
@jbcrail, does this make sense?
