### ISSUE TITLE
Build issue regarding taxcalc version bump causing other version bumps

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/policybrain-builder#4]
Preamble:
 * We used to have a custom build set up for each of Tax-Calculator, OG-USA, B-Tax
 * We made this policybrain-builder repo to have a build script for all packages
 * We recently fixed the `build_release.sh` script here to make sure that OG-USA and B-Tax packages, when built with a new git tag, are built with the latest `taxcalc` as a dependency. 
 * `build_release.sh` may be used to build 1 to 3 of these repos by using the env vars `SKIP_BTAX`, `SKIP_OGUSA`
Problem:
 * When Tax-Calculator is built as version like `5.0.0`, then that means B-Tax and/or OG-USA also need a new version tag.  The reason for this new version tag for B-Tax and OG-USA is that the existing version tags for them will be tied to a prior taxcalc, such as `4.9.9` in the example.  

Let's use this issue as reminder to bump versions of B-Tax, OG-USA and also reminder that Tax-Calculator versions are pinned in B-Tax, OG-USA

**Comment by martinholmer** [comment]
Pull request #52 by @jbcrail made issue #4 obsolete. Thanks, @jbcrail.
Should this issue be closed? If so, somebody else will have to do that because I can't.

**Comment by jbcrail** [comment]
The new CLI makes this obsolete.
