### ISSUE TITLE
Fix anaconda upload with --force

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/policybrain-builder#42]
There are some errors uploading a package that already has been uploaded in the existing script run that don't seem to cause problems.  Look into `anaconda upload`

**Comment by martinholmer** [comment]
Pull request #52 by @jbcrail made issue #42 obsolete. Thanks, @jbcrail.
Should this issue be closed? If so, somebody else will have to do that because I can't.

**Comment by jbcrail** [comment]
This was resolved with the new CLI.
