### ISSUE TITLE
Better default for env variable `OSPC_PYTHONS`

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/policybrain-builder#43]
Better default for env variable `OSPC_PYTHONS` - it defaults to "", leaving an confusing error, e.g.:

```
$ SKIP_ANACONDA_UPLOAD=1 TAXCALC_TAG=0.9.0 . ./build_release.sh
######## STATUS ## Build for Python ######## ########
FAILED
```

**Comment by martinholmer** [comment]
The `README.md` documentation says this:
> Control which versions of Python are built:
>
> `export OSPC_PYTHONS="2.7 3.4 3.5 3.6";`
>
> By default it builds for 2.7 3.4 3.5 3.6 and may error out on some

First of all, we have not been creating conda packages for Python 3.4 for some time now.
So, that needs to be corrected.

Second, the last line implies that the `build_release.sh` script contains a default value of `OSPC_PYTHONS`, but I didn't see any such default definition in the script.  Am I missing something?  Which is wrong: the script or the documentation?
