### ISSUE TITLE
Error proofing for local running of build_release.sh

### ISSUE THREAD

**Issue by PeterDSteinberg** [open-source-economics/policybrain-builder#45]
* [ ] Avoid accidental upload:
     * [x] Review / change the usage of `anaconda upload --force`
     * [ ] Review / change the file name spec passed to `anaconda upload`
* [ ] Allow builds from tags / branches from personal forks
* [x] Configure to which anaconda org user name it uploads?  Currently set to `ospc`.  This would require the CI user of this script to add tokens to their build config.
* [x] Consider decoupling to some extent the build process.  Currently it always builds `taxcalc=A.B.C` first because it pins `ogusa` and `btax` to `>=A.B.C` by programmatically altering their conda recipes
* [ ] Allow the build_release.sh user to change the package file name, e.g. building branch of X of `taxcalc` but naming the released packages by something other than X

**Comment by martinholmer** [comment]
Pull request #52 by @jbcrail made issue #45 obsolete.  Thanks, @jbcrail.
Should this issue be closed?  If so, somebody else will have to do that because I can't.

**Comment by jbcrail** [comment]
The remaining subtasks involve building packages from either non-master branches or personal forks. This functionality is not in the latest CLI.

@martinholmer, @MattHJensen Is this needed? If not, we can close this issue.

**Comment by martinholmer** [comment]
@jbcrail said:
> The remaining subtasks [in #45] involve building packages from either non-master branches or personal forks. This functionality is not in the latest CLI.
>
> Is this needed? If not, we can close this issue.

Tax-Calculator has its own (much faster) way of doing this, so Tax-Calculator does not need or expect these capabilities from `policybrain-builder`.  If other repos do want this kind of capability, they can adapt the [tax-calculator/conda.recipe/install_local_taxcalc_package.sh](https://github.com/open-source-economics/Tax-Calculator/blob/master/conda.recipe/install_local_taxcalc_package.sh) to work in other repos.

So, I would recommend closing #45 and accepting our congratulations for a job very well done.

 @MattHJensen @jdebacker @rickecon

**Comment by MattHJensen** [comment]
@jbcrail, do you agree with @martinholmer that this should be closed (also resolving #66)?

**Comment by martinholmer** [comment]
@jbcrail and @MattHJensen,
I don't have permission to close issue #45.
Can one of you close this obsolete issue?
Thanks.

**Comment by jbcrail** [comment]
I agree this should be closed.
