### ISSUE TITLE
How to build and upload conda taxcalc packages for a specified release?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#46]
Tax-Calculator developers already have the ability to build and locally install a conda taxcalc package, use it, test it, and then uninstall it from the local computer.

How can Tax-Calculator developers build the full range (OS x Python) of taxcalc packages for a specified release and upload them to the ospc master channel without doing anything with OG-USA or B-Tax or any other model?  RIght now, the `build_release.sh` script seems to not work and is excessively complicated for this simple taxcalc build/upload task. 

It would be more convenient for this taxcalc build/upload script to be part of the Tax-Calculator repository because it has nothing to do with the other OSPC models.

@MattHJensen @PeterDSteinberg @jbcrail

**Comment by PeterDSteinberg** [comment]
@martinholmer Let's fix the `build_release.sh` script as needed for what you are working on and document the missing steps.  We used to have separate but nearly identical build scripts in Tax-Calculator and OG-USA and that had its own frustrations.  Can you post your error?  Make sure you have defined the `OSPC_PYTHONS` environment variable and review the open issues here that may related to your bug.

I just confirmed I could run:
```
SKIP_ANACONDA_UPLOAD=1 TAXCALC_TAG=0.9.0 OSPC_PYTHONS="2.7" . ./build_release.sh
```

**Comment by martinholmer** [comment]
@PeterDSteinberg said:
> Let's fix the build_release.sh script as needed for what you are working on and document the missing steps. We used to have separate but nearly identical build scripts in Tax-Calculator and OG-USA and that had its own frustrations. Can you post your error? Make sure you have defined the OSPC_PYTHONS environment variable and review the open issues here that may related to your bug.
>
> I just confirmed I could run:
>
> ```
> SKIP_ANACONDA_UPLOAD=1 TAXCALC_TAG=0.9.0 OSPC_PYTHONS="2.7" . ./build_release.sh
> ```

Thanks for the tip, @PeterDSteinberg.  You should have something like this in the `README.md` documentation.  I added `SKIP_OGUSA=1 SKIP_BTAX=1` and everything worked fine after I upgraded my version of conda-client.

The next step for me is to be able to remove the `SKIP_ANACONDA_UPLOAD=1` part, but to do that I need the secret `ospc` user Anaconda token.

**Comment by martinholmer** [comment]
@PeterDSteinberg, Can you please send to me via private email the TOKEN for the anaconda.org `ospc` user?  I need it to make the `build_release.sh` script work without `SKIP_ANACONDA_UPLOAD=1`.

@MattHJensen

**Comment by martinholmer** [comment]
@PeterDSteinberg and @MattHJensen,
I'm successfully using the jenkins_uploader TOKEN for the anaconda ospc user, so I'm closing #46.
