### ISSUE TITLE
Question about pb option --python

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#53]
Following the merge of pull request #52, I experimented with the new CLI pb capability.
Thank you, @jbcrail, for this major improvement.

But I couldn't get the --python option to work.  Maybe I don't understand how to release packages only for Python 2.7 (for testing).  Here is what I tried and the error message I got with each try:
```
iMac2:policybrain-builder mrh$ pb --help
Usage: pb [OPTIONS] COMMAND [ARGS]...

  Manage Open Source Policy Center (OSPC) packages.

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  build    Build packages.
  release  Release packages.
  upload   Upload packages.
iMac2:policybrain-builder mrh$ pb release --python 2.7 taxcalc=0.1.5
Error: --python option requires 3 arguments
iMac2:policybrain-builder mrh$ pb release --python "2.7" taxcalc=0.1.5
Error: --python option requires 3 arguments
iMac2:policybrain-builder mrh$ pb release --python="2.7" taxcalc=0.1.5
Error: --python option requires 3 arguments
iMac2:policybrain-builder mrh$ pb release --python=2.7 taxcalc=0.1.5
Error: --python option requires 3 arguments
iMac2:policybrain-builder mrh$ 
```

Also, notice that if I adhere to the --help information about how to order command-line arguments, I have a different kind of problem.
```
iMac2:policybrain-builder mrh$ pb --python=2.7 release taxcalc=0.1.5
Error: no such option: --python
```
Maybe the --help line that says `Usage: pb [OPTIONS] COMMAND [ARGS]...` should be revised?

But my main question, @jbcrail, is how to limit the Python versions to just one (e.g., 2.7).
I didn't have any luck with the OSPC_PYTHONS environment variable either.
What am I doing wrong?

**Comment by jbcrail** [comment]
@martinholmer Your issue was caused by a bug with the flag configuration. PR #55 fixes the broken `--python` flag and the `OSPC_PYTHONS` environment variable.

**Comment by martinholmer** [comment]
@jbcrail,  Thanks so much for the quick fix of the pb `--python` option
