### ISSUE TITLE
Question about naming of the conda packages

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#54]
Following the merge of pull request #52, I experimented with the new CLI pb capability.
Thank you, @jbcrail, for this major improvement.

My experiment involved creating release 0.1.5 with the HEAD of the Tax-Calculator master branch and then running the following script:
```
TOKEN=a-deep-secret
pb release --token $TOKEN --label main taxcalc=0.1.5
```
After a little more than twenty minutes, all 15 of the conda packages were on anaconda.org.
So, everything worked smoothly.

However, the names of the 0.1.5 packages are very strange and confusing to anybody not immersed in the conda-packaging world.  And the names are different than when the packages were made with the old bash shell script.  Here is what I saw after running my experiment:
```
iMac2:tax-calculator mrh$ conda search -c ospc taxcalc | grep -e 0.9 -e 0.1.5
taxcalc                      0.1.5            py27ha32e829_0  ospc            
                             0.9.0                    py27_0  ospc            
                             0.9.0                    py35_0  ospc            
                             0.9.0                    py36_0  ospc            
                             0.9.1                    py27_0  ospc            
                             0.9.1                    py35_0  ospc            
                             0.9.1                    py36_0  ospc            
                             0.9.2                    py27_0  ospc            
                             0.9.2                    py35_0  ospc            
                             0.9.2                    py36_0  ospc            
iMac2:tax-calculator mrh$ 
```
What is this inscrutable string `ha32e829` mean?
Can we get rid of it so that the new package names look like the old package names?
The reason for this is that we ask non-developers to download the taxcalc package (in order to use the Tax-Calculator CLI, tc) and we would like to make this process as "non-scary" as possible.

**Comment by jbcrail** [comment]
@martinholmer I wasn't sure either, but after some research, `conda build` v3 uses a hash as a unique identifier. I developed the new CLI using v2, so I didn't see the auto-generated build string. Fortunately there's a `--old-build-string` flag that can toggle the old behavior.

You can see a [Continuum blog post](https://www.continuum.io/blog/developer-blog/package-better-conda-build-3) or the [conda docs](https://conda.io/docs/building/variants.html#differentiating-packages-built-with-different-variants) for more details.
