### ISSUE TITLE
CLI upload ignores --python option

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#56]
@jbcrail,
Using testing release 0.1.5 (containing the HEAD of Tax-Calculator master), I can execute this command:
```
pb release --python "2.7" taxcalc=0.1.5
```
and it runs to completion.  As I expected after PR#55, only five packages were build (one each for the five platforms and all for Python 2.7). So far so good.

But then when the uploads started, `pb` uploaded all fifteen packages (not just the five for Python 2.7).  I'm not sure where the other ten came from but this upload behavior is not compatible with the build behavior.  When looking at the `packages.py` file, the `build` method used the `py_versions` argument while the `upload` method does not have `py_versions` as an argument.

Can the same py_versions logic as is in `build` be added to `upload`?

Or did I do something wrong?  Maybe there is a way to upload only the five Python 2.7 packages that I'm not aware of.

**Comment by jbcrail** [comment]
@martinholmer This was an omission on my part. I had used a wildcard to upload all packages together, but this caused the issue that you saw.
