### ISSUE TITLE
Question: how to use pb CLI to release packages for btax 0.1.9 ?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#64]
@jbcrail,  Can you show how to use `pb` to release btax 0.1.9 using a specified verion of taxcalc?
Is it something like this?
```
pb release --clean --token $TOKEN --label main --only-last taxcalc=0.10.0 btax=0.1.9
```
My worry is this might **recreate** the taxcalc 0.10.0 packages, which is not only unnecessarily time consuming but also potentially risky.  Is that what the `--only-last` flag does?  Does it mean that only the last named package (in this case, `btax=0.1.9`) is built and uploaded to anaconda.org?

Is the above example how to tell `pb` to **use** (but not build or upload) a specified taxcalc pacakge?

Also, now that developers besides me are starting to use policybrain-builder, the README documentation is very confusing.  Shouldn't the README-cli.md file be renamed README.md?  And shouldn't the old `build_release.sh` bash script be removed from the repo?

@MattHJensen @jdebacker

**Comment by jbcrail** [comment]
@martinholmer, your syntax and its meaning is correct.

The `--only-last` flag will only run the specified command (in this case, `release`) for the topmost dependency in the list (i.e., `btax`). The taxcalc version is only used when updating B-Tax's `conda.recipe/meta.yaml` to specify the exact version. The taxcalc repository is never cloned nor is the package built and uploaded.

Regarding the documentation, I agree it's time to replace the README and remove the bash script. I'll create a PR to do this and close #3.

**Comment by martinholmer** [comment]
@jbcrail,  Thanks for the quick feedback.  And the clean-up of the documentation will help others who have not been following you work.

@MattHJensen @jdebacker

**Comment by martinholmer** [comment]
@jbcrail,  Thanks again for your quick responses to issue #64.  Closing #64 now.
