### ISSUE TITLE
How to use pb --python option?

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#69]
I could not find any documentation or example of how to use the `pb release --python` option.
Not using the option causes `pb` to build five packages (for different operating systems) for each of three Python versions: 2.7, 3.5, 3.6.  That's fifteen packages in total.

I can see how to specify just one Python version: `pb release --python 2.7` for example.

But what I haven't figured out is the syntax of specifying two Python versions.
For example, `--python 2.7,3.6` didn't seem to work and neither did `--python "2.7 3.6"`.

So, @jbcrail, can the `README.md` documentation be updated to provide examples of how to specify the `pb release --python` option?

After further experimentation, it seems as if the `pb release --python` option may have a bug that prevents it from working correctly.

@MattHJensen @jdebacker @jbcrail

**Comment by jbcrail** [comment]
@martinholmer The `click` library requires a separate flag for specifying two or more values (e.g. `--python 2.7 --python 3.6`). I updated the documentation to show how to use it.
