### ISSUE TITLE
BUG: pb no longer respects user's conda always_yes setting

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/policybrain-builder#73]
Last summer `pb` was fixed to resolve issue #51, but my testing today (Oct 24, 2017) after the recent bug fixes, suggests that `pb` no longer has this desirable feature.

@jbcrail, the bug fixes you made today are great, but this apparent regression needs to be fixed.  It's not just a convenience issue, there are safety concerns for users who rely on the yes/no prompt when using conda.

**Comment by jbcrail** [comment]
Could you re-run the command with `-vvv` added and paste the results? Also, could you paste the results of `conda --version`?

**Comment by martinholmer** [comment]
On further investigation, the bug in issue #73 is even a bigger problem that I first reported.  Now `pb` is messing with my ~/.condarc file.  This is highly impolite and totally inappropriate for a script to alter a user's personal settings.  Here is the time stamp and contents of that file:
```
iMac2:~ mrh$ ls -l .condarc
-rw-r--r--  1 mrh  staff  17 Oct 24 18:22 .condarc
iMac2:~ mrh$ cat .condarc
always_yes: true
iMac2:~ mrh$ 
```
@jbcrail, I don't understand why the recent bug fixes cause this serious regression in `pb` behavior.

**Comment by martinholmer** [comment]
@jbcrail,  Here is the conda version info you requested:
```
iMac2:~ mrh$ conda --version
conda 4.3.30
```
I'm not keen on running the `pb release` command again because it takes more than 20 minutes to run.

The problem is clear: `pb` is revising my `~/.condarc` file and then failing to set it back to the way it was before the `pb` job.  It used to do that, but somehow `pb` is not remembering the old contents and writing it back at the end.

**Comment by jbcrail** [comment]
`set_and_rollback_conda_config` in `utils.py` is the only place that controls this setting. I don't see how the recent bug fixes would've change the setting.

Instead of running `pb release`, could you run `pb build`? This will simulate the same behavior without taking as long. You can also reduce the time taken by only building for 2.7 or only one repo.

**Comment by martinholmer** [comment]
@jbcrail,  You can use the test Tax-Calculator release 0.1.0 to do the `pb` debugging.  Here is what I ran in a bash shell script:
```
TOKEN=<secret>
OPTIONS="--token $TOKEN --clean --python 2.7 --python 3.6 --label main"
pb release $OPTIONS taxcalc=$1 2>&1 | awk '$1~/\[taxcalc\]/'
```
And this is what I got:
```
iMac2:policybrain-builder mrh$ ./taxcalc-package.sh 0.1.0
STARTING : Tue Oct 24 18:04:30 EDT 2017
[taxcalc] removing
[taxcalc] cloning
[taxcalc] fetching
[taxcalc] checking out '0.1.0'
[taxcalc] archiving
[taxcalc] building 3.6
[taxcalc] converting to linux-32
[taxcalc] converting to linux-64
[taxcalc] converting to win-32
[taxcalc] converting to win-64
[taxcalc] building 2.7
[taxcalc] converting to linux-32
[taxcalc] converting to linux-64
[taxcalc] converting to win-32
[taxcalc] converting to win-64
[taxcalc] uploading osx-64 packages
[taxcalc] uploading linux-32 packages
[taxcalc] uploading linux-64 packages
[taxcalc] uploading win-32 packages
[taxcalc] uploading win-64 packages
FINISHED : Tue Oct 24 18:22:27 EDT 2017
iMac2:policybrain-builder mrh$ 
```

**Comment by jbcrail** [comment]
Could you add `-vvv` (full verbosity) to `OPTIONS`, remove awk, and re-run? I need to see the `DEBUG` and `INFO` logs.

For example, here are my results for `pb build` (though I modified the command to not actually do the build, thus, testing the conda setting):
```
(policybrain) 0277-jcrail:jcrail policybrain-builder$ conda --version
conda 4.3.30
(policybrain) 0277-jcrail:jcrail policybrain-builder$ ls -l ~/.condarc
-rw-r--r--  1 jcrail  staff  109 Oct 24 15:53 /Users/jcrail/.condarc
(policybrain) 0277-jcrail:jcrail policybrain-builder$ cat ~/.condarc | grep always_yes
always_yes: false
(policybrain) 0277-jcrail:jcrail policybrain-builder$ pb build -vvv --only-last --python 2.7 taxcalc=0.9.1 btax
DEBUG: conda config --get always_yes
INFO: saved previous conda config: always_yes
DEBUG: conda config --set always_yes True
INFO: changed conda config: always_yes True
DEBUG: conda config --set always_yes False

INFO: restored previous conda config: always_yes
(policybrain) 0277-jcrail:jcrail policybrain-builder$ cat ~/.condarc | grep always_yes
always_yes: false
(policybrain) 0277-jcrail:jcrail policybrain-builder$ ls -l ~/.condarc
-rw-r--r--  1 jcrail  staff  109 Oct 24 15:54 /Users/jcrail/.condarc
```

Because `conda config` changes `.condarc` when updating the setting, the timestamp will always be different after running `pb`.

**Comment by martinholmer** [comment]
OK, after running the following script, it appears that everything is running fine.

My apologies for raising what seems like a false alarm.

After editing the ~/.condarc file to contain `always_yes: false`, I ran this script:
```
cat ~/.condarc
OPTIONS="--token $TOKEN --clean --python 2.7"
pb release $OPTIONS taxcalc=$1 2>&1 | awk '$1~/\[taxcalc\]/'
cat ~/.condarc
```
and got this output:
```
STARTING : Tue Oct 24 18:58:48 EDT 2017
always_yes: false     <--------------------
[taxcalc] removing
[taxcalc] cloning
[taxcalc] fetching
[taxcalc] checking out '0.1.0'
[taxcalc] archiving
[taxcalc] building 2.7
[taxcalc] converting to linux-32
[taxcalc] converting to linux-64
[taxcalc] converting to win-32
[taxcalc] converting to win-64
[taxcalc] uploading osx-64 packages
[taxcalc] uploading linux-32 packages
[taxcalc] uploading linux-64 packages
[taxcalc] uploading win-32 packages
[taxcalc] uploading win-64 packages
always_yes: false     <--------------------
FINISHED : Tue Oct 24 19:06:17 EDT 2017
```

So, again, sorry for wasting your time.
The bug fixes you implemented today are really great!
Thanks for making this tool, which is critical to our projects.

@MattHJensen

**Comment by martinholmer** [comment]
@jbcrail,  I'm closing the bogus issue #73. Thanks again for all the great help.

**Comment by jbcrail** [comment]
@martinholmer You're welcome. The verbose option is helpful for testing assumptions and seeing what's really going on.
